version: '1.0'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    env_file: ./.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"

