// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/7/2026, 12:31:47 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/norbert/finish-school-project/audio-classification/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/norbert/finish-school-project/audio-classification/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/norbert/finish-school-project/audio-classification/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/norbert/finish-school-project/audio-classification/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/norbert/finish-school-project/audio-classification/frontend/app/plugins/**/*.{js,ts,mjs}","/home/norbert/finish-school-project/audio-classification/frontend/app/composables/**/*.{js,ts,mjs}","/home/norbert/finish-school-project/audio-classification/frontend/app/utils/**/*.{js,ts,mjs}","/home/norbert/finish-school-project/audio-classification/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/norbert/finish-school-project/audio-classification/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/norbert/finish-school-project/audio-classification/frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;