// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('/home/norbert/finish-school-project/audio-classification/frontend/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
interface SessionData {
  id: string | number
}
}
