name: audio-genre-classification ci pipline

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build BE Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: audio-classification-backend:latest

      - name: build FE Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: audio-classification-frontend:latest
